/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TurmasImport } from './routes/turmas'
import { Route as NotificacoesImport } from './routes/notificacoes'
import { Route as MinhasAtividadesImport } from './routes/minhas-atividades'
import { Route as LogoutImport } from './routes/logout'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as CriarAtividadeImport } from './routes/criar-atividade'
import { Route as AtividadesDoAlunoImport } from './routes/atividades-do-aluno'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TurmasRoute = TurmasImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => rootRoute,
} as any)

const NotificacoesRoute = NotificacoesImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRoute,
} as any)

const MinhasAtividadesRoute = MinhasAtividadesImport.update({
  id: '/minhas-atividades',
  path: '/minhas-atividades',
  getParentRoute: () => rootRoute,
} as any)

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const CriarAtividadeRoute = CriarAtividadeImport.update({
  id: '/criar-atividade',
  path: '/criar-atividade',
  getParentRoute: () => rootRoute,
} as any)

const AtividadesDoAlunoRoute = AtividadesDoAlunoImport.update({
  id: '/atividades-do-aluno',
  path: '/atividades-do-aluno',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/atividades-do-aluno': {
      id: '/atividades-do-aluno'
      path: '/atividades-do-aluno'
      fullPath: '/atividades-do-aluno'
      preLoaderRoute: typeof AtividadesDoAlunoImport
      parentRoute: typeof rootRoute
    }
    '/criar-atividade': {
      id: '/criar-atividade'
      path: '/criar-atividade'
      fullPath: '/criar-atividade'
      preLoaderRoute: typeof CriarAtividadeImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/minhas-atividades': {
      id: '/minhas-atividades'
      path: '/minhas-atividades'
      fullPath: '/minhas-atividades'
      preLoaderRoute: typeof MinhasAtividadesImport
      parentRoute: typeof rootRoute
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesImport
      parentRoute: typeof rootRoute
    }
    '/turmas': {
      id: '/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof TurmasImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atividades-do-aluno': typeof AtividadesDoAlunoRoute
  '/criar-atividade': typeof CriarAtividadeRoute
  '/dashboard': typeof DashboardRoute
  '/logout': typeof LogoutRoute
  '/minhas-atividades': typeof MinhasAtividadesRoute
  '/notificacoes': typeof NotificacoesRoute
  '/turmas': typeof TurmasRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atividades-do-aluno': typeof AtividadesDoAlunoRoute
  '/criar-atividade': typeof CriarAtividadeRoute
  '/dashboard': typeof DashboardRoute
  '/logout': typeof LogoutRoute
  '/minhas-atividades': typeof MinhasAtividadesRoute
  '/notificacoes': typeof NotificacoesRoute
  '/turmas': typeof TurmasRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/atividades-do-aluno': typeof AtividadesDoAlunoRoute
  '/criar-atividade': typeof CriarAtividadeRoute
  '/dashboard': typeof DashboardRoute
  '/logout': typeof LogoutRoute
  '/minhas-atividades': typeof MinhasAtividadesRoute
  '/notificacoes': typeof NotificacoesRoute
  '/turmas': typeof TurmasRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atividades-do-aluno'
    | '/criar-atividade'
    | '/dashboard'
    | '/logout'
    | '/minhas-atividades'
    | '/notificacoes'
    | '/turmas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atividades-do-aluno'
    | '/criar-atividade'
    | '/dashboard'
    | '/logout'
    | '/minhas-atividades'
    | '/notificacoes'
    | '/turmas'
  id:
    | '__root__'
    | '/'
    | '/atividades-do-aluno'
    | '/criar-atividade'
    | '/dashboard'
    | '/logout'
    | '/minhas-atividades'
    | '/notificacoes'
    | '/turmas'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtividadesDoAlunoRoute: typeof AtividadesDoAlunoRoute
  CriarAtividadeRoute: typeof CriarAtividadeRoute
  DashboardRoute: typeof DashboardRoute
  LogoutRoute: typeof LogoutRoute
  MinhasAtividadesRoute: typeof MinhasAtividadesRoute
  NotificacoesRoute: typeof NotificacoesRoute
  TurmasRoute: typeof TurmasRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtividadesDoAlunoRoute: AtividadesDoAlunoRoute,
  CriarAtividadeRoute: CriarAtividadeRoute,
  DashboardRoute: DashboardRoute,
  LogoutRoute: LogoutRoute,
  MinhasAtividadesRoute: MinhasAtividadesRoute,
  NotificacoesRoute: NotificacoesRoute,
  TurmasRoute: TurmasRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/atividades-do-aluno",
        "/criar-atividade",
        "/dashboard",
        "/logout",
        "/minhas-atividades",
        "/notificacoes",
        "/turmas"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/atividades-do-aluno": {
      "filePath": "atividades-do-aluno.tsx"
    },
    "/criar-atividade": {
      "filePath": "criar-atividade.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/minhas-atividades": {
      "filePath": "minhas-atividades.tsx"
    },
    "/notificacoes": {
      "filePath": "notificacoes.tsx"
    },
    "/turmas": {
      "filePath": "turmas.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
